language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env: COVERAGE=yes
    - php: hhvm
    - php: nightly
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
    - php: 7.3
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $TRAVIS_PHP_VERSION != 7.3 && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - if [[ $COVERAGE = yes ]]; then vendor/bin/phpunit --verbose --coverage-clover=coverage.clover; else vendor/bin/phpunit --verbose; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi